# è®¡ç®—æ‰€æœ‰æ•°æ®åŒ…ï¼ˆå³å¯ç”¨ /riabandwidthsaver unfiltered çš„ç»Ÿè®¡ä¿¡æ¯ï¼‰
calcAllPackets: true

message:
  playerEcoEnable: 'Â§ağŸƒ ECO èŠ‚èƒ½æ¨¡å¼å·²å¯ç”¨ï¼Œæ¸¸æˆä¸–ç•Œæ›´æ–°å¯èƒ½ä¼šå»¶è¿Ÿã€‚'
  playerEcoDisable: 'Â§8ğŸƒ ECO èŠ‚èƒ½æ¨¡å¼å·²åœç”¨ã€‚'